### ISSUE TITLE
Fix Memory Leaks

### ISSUE THREAD

**Issue by james-s-willis** [kotekan/kotekan#510]
I found some memory leaks when running with the address sanitizer: `cmake -DSANITIZE=ON -DCMAKE_BUILD_TYPE=Debug ..`.

```
=================================================================
==17185==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 47520 byte(s) in 660 object(s) allocated from:
    #0 0x7f947cf81662 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98662)
    #1 0xf0de31 in create_metadata /home/james/Work/CHIME/kotekan/lib/core/metadata.c:12
    #2 0xf0e8cb in create_metadata_pool /home/james/Work/CHIME/kotekan/lib/core/metadata.c:91
    #3 0xf10556 in kotekan::metadataFactory::new_pool(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/james/Work/CHIME/kotekan/lib/core/metadataFactory.cpp:66
    #4 0xf0fd72 in kotekan::metadataFactory::build_from_tree(std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, metadataPool*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, metadataPool*> > >&, nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::adl_serializer>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/james/Work/CHIME/kotekan/lib/core/metadataFactory.cpp:47
    #5 0xf0f558 in kotekan::metadataFactory::build_pools[abi:cxx11]() /home/james/Work/CHIME/kotekan/lib/core/metadataFactory.cpp:24
    #6 0xf0ac73 in kotekan::kotekanMode::initalize_stages() /home/james/Work/CHIME/kotekan/lib/core/kotekanMode.cpp:63
    #7 0xb385b5 in start_new_kotekan_mode(kotekan::Config&, bool) /home/james/Work/CHIME/kotekan/kotekan/kotekan.cpp:270
    #8 0xb3c9c3 in main /home/james/Work/CHIME/kotekan/kotekan/kotekan.cpp:396
    #9 0x7f947c1c482f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

Direct leak of 128 byte(s) in 1 object(s) allocated from:
    #0 0x7f947cf81662 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98662)
    #1 0x7f947ca9a7d5 in event_new /home/james/Install/libevent-2.1.11-stable/event.c:2214

Direct leak of 120 byte(s) in 4 object(s) allocated from:
    #0 0x7f947cf4b34f in strdup (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x6234f)
    #1 0xe82955 in create_buffer /home/james/Work/CHIME/kotekan/lib/core/buffer.c:70
    #2 0xe8f3b4 in kotekan::bufferFactory::new_buffer(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/james/Work/CHIME/kotekan/lib/core/bufferFactory.cpp:76
    #3 0xe8e5b6 in kotekan::bufferFactory::build_from_tree(std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Buffer*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Buffer*> > >&, nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::adl_serializer>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/james/Work/CHIME/kotekan/lib/core/bufferFactory.cpp:48
    #4 0xe8e68d in kotekan::bufferFactory::build_from_tree(std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Buffer*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Buffer*> > >&, nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::adl_serializer>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/james/Work/CHIME/kotekan/lib/core/bufferFactory.cpp:54
    #5 0xe8dd9e in kotekan::bufferFactory::build_buffers[abi:cxx11]() /home/james/Work/CHIME/kotekan/lib/core/bufferFactory.cpp:25
    #6 0xf0ad5e in kotekan::kotekanMode::initalize_stages() /home/james/Work/CHIME/kotekan/lib/core/kotekanMode.cpp:71
    #7 0xb385b5 in start_new_kotekan_mode(kotekan::Config&, bool) /home/james/Work/CHIME/kotekan/kotekan/kotekan.cpp:270
    #8 0xb3c9c3 in main /home/james/Work/CHIME/kotekan/kotekan/kotekan.cpp:396
    #9 0x7f947c1c482f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

Direct leak of 40 byte(s) in 1 object(s) allocated from:
    #0 0x7f947cf4b34f in strdup (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x6234f)
    #1 0xb3bff2 in main /home/james/Work/CHIME/kotekan/kotekan/kotekan.cpp:319
    #2 0x7f947c1c482f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

SUMMARY: AddressSanitizer: 47808 byte(s) leaked in 666 allocation(s).
```

Me and @nritsche have fixed the ones inside `kotekan`, a PR will follow. The remaining leak is inside `libevent`, but we don't know how to ignore this one with `gcc`. There is an option: `-fsanitize-blacklist=blacklist.txt` for the `clang` compiler.

We think this test should also be added to the CI server.

**Comment by jrs65** [comment]
I don't think this is one for me. I'm going to unassign myself.
