### ISSUE TITLE
CI: install python future

### ISSUE THREAD

**Issue by nritsche** [kotekan/kotekan#772]
From the build log:
```
[  3%] Generating version.c
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "kotekan/__init__.py", line 3, in <module>
    from future.builtins import *  # noqa  pylint: disable=W0401, W0614
ImportError: No module named future.builtins
Scanning dependencies of target kotekan_version
[  4%] Building C object lib/version/CMakeFiles/kotekan_version.dir/version.c.o
```

**Comment by nritsche** [comment]
`future` is already installed in the Dockerfile. Maybe kotekan uses a different python version than 3.7 here.
